### ISSUE TITLE
error code EAUDITNOPJSON error audit No package.json found: Cannot audit a project without a package.json

### ISSUE THREAD

**Issue by marcelocecin** [alfred82santa/whalesong#1]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'audit', 'fix' ]
2 info using npm@6.1.0
3 info using node@v8.9.1
4 verbose npm-session f7c3fce32977bd48
5 verbose stack Error: No package.json found: Cannot audit a project without a package.json
5 verbose stack     at Bluebird.all.spread (/usr/local/lib/node_modules/npm/lib/audit.js:139:19)
5 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
5 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:509:35)
5 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
5 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
5 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
5 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
5 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
5 verbose stack     at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:144:14)
5 verbose stack     at PromiseArray._iterate (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:114:31)
5 verbose stack     at PromiseArray.init [as _init] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:78:10)
5 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
5 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
5 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
5 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
5 verbose stack     at PromiseArray._resolve (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise_array.js:126:19)
6 verbose cwd /Users/marcelocecin/Downloads/whalesong-master
7 verbose Darwin 18.0.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "audit" "fix"
9 verbose node v8.9.1
10 verbose npm  v6.1.0
11 error code EAUDITNOPJSON
12 error audit No package.json found: Cannot audit a project without a package.json
13 verbose exit [ 1, true ]

**Comment by alfred82santa** [comment]
What did you try to do? Which command did you execute?

**Comment by marcelocecin** [comment]
`$ make requirements`

**Comment by alfred82santa** [comment]
It's strange. I've test it right now (cloning repo again) and it works.

Your problem seem to be about package.json file. It didn't find it. But it is in repo: https://github.com/alfred82santa/whalesong/blob/master/js/package.json

**Comment by marcelocecin** [comment]
`$ git clone https://github.com/alfred82santa/whalesong.git`
`$ make requirements`
`$ python3 setup.py install`
`$ python3 minibot.py`
error: Traceback (most recent call last):
  File "minibot.py", line 7, in <module>
    from whalesong import Whalesong
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/whalesong-0.2.0-py3.6.egg/whalesong/__init__.py", line 3, in <module>
    from whalesong.managers.chat import ChatCollectionManager
ModuleNotFoundError: No module named 'whalesong.managers'

**Comment by anderson-paiva** [comment]
Change setup.py file:

# from setuptools import setup
from setuptools import setup, find_packages
.
.
.
    #packages=[PACKAGE_NAME, ],
    packages=find_packages(exclude=['examples*']),
    package_data={PACKAGE_NAME: ['**/*.js']},
.
.
.

**Comment by alfred82santa** [comment]
mmm are you trying to install it? to early I think...

**Comment by alfred82santa** [comment]
@marcelocecin 

try to follow my instructions:

* You don't need to install package to test examples. In fact, I haven't checked setup.py, yet. I'm not sure it works.

```bash
$ git clone https://github.com/alfred82santa/whalesong.git
$ cd whalesong
$ make requirements
$ make build-js
$ PYTHONPATH=.:$PYTHONPATH python3 examples/minibot.py
```

In order to execute examples you must add current directory to python path.

**Comment by alfred82santa** [comment]
New version fix python package. Now you can install it from pypi.

**Comment by DCTips** [comment]
I am also facing the same problem.
So i navigate to the exact subfolder where the package.json file is located and then run the npm audit fix command and it worked very well.

**Comment by powellkarind** [comment]
@DCTips -- thank you! I found that exact subfolder on my Windows 10 system: C:\Users\Karin\AppData\Roaming\npm\node_modules\npm
