### ISSUE TITLE
If I logout in my phone, how I can check it in Whalesong?

### ISSUE THREAD

**Issue by Tingaev** [alfred82santa/whalesong#100]
Only Stream: Stream.DISCONNECTED?

**Comment by DSchndr** [comment]
Check [this value](https://whalesong.readthedocs.io/en/latest/api/conn.html#whalesong.managers.conn.Conn.connected).

**Comment by alfred82santa** [comment]
You could use the property that @DSchndr mentions. It is a calculated property based on value of `stream` property in `stream` object (that you mention).

https://whalesong.readthedocs.io/en/latest/api/stream.html#whalesong.managers.stream.Stream.stream

**Comment by Tingaev** [comment]
@alfred82santa when i run your example minibot.py I get once stream value DICSONNECTED. I can not get this value before auth my number?
