### ISSUE TITLE
63 vulnerabilities found - Creating react app

### ISSUE THREAD

**Issue by moq742** [alfred82santa/whalesong#104]
Hello, I am trying to create a react app but it gives me 63 vulnerabilities, I am a new user of react and if someone experienced can help me setup my project that would be much appreciated. Thank you in advance. 

iMacbook-Pro:can-game sam$.  create-react-app can-game

Creating a new React app in /Users/sam/Desktop/can-game.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

> fsevents@1.2.7 install /Users/sam/Desktop/can-game/node_modules/chokidar/node_modules/fsevents
> node install

[fsevents] Success: "/Users/sam/Desktop/can-game/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.4 install /Users/sam/Desktop/can-game/node_modules/fsevents
> node install

[fsevents] Success: "/Users/sam/Desktop/can-game/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ react@16.8.4
+ react-scripts@2.1.8
+ react-dom@16.8.4
added 1974 packages from 735 contributors and audited 36232 packages in 54.031s
**found 63 low severity vulnerabilities**
  run `npm audit fix` to fix them, or `npm audit` for details

Initialized a git repository.

Success! Created can-game at /Users/sam/Desktop/can-game
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd can-game
  npm start

Happy hacking!
iMacbook-Pro:Desktop sam$ npm audit fix
npm ERR! code EAUDITNOPJSON
npm ERR! audit No package.json found: Cannot audit a project without a package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2019-03-14T04_59_30_573Z-debug.log

**Comment by parthibd** [comment]
This is not where you create issues regarding react .

**Comment by parthibd** [comment]
Please close this issue.
