### ISSUE TITLE
--single-process is not supported in windows

### ISSUE THREAD

**Issue by vasani-arpit** [alfred82santa/whalesong#105]
**Describe the bug**
So I was trying to run this on windows PC and chrome was throwing an error due to `--single-process` flag in [driver_chromium.py](https://github.com/alfred82santa/whalesong/blob/master/whalesong/driver_chromium.py#L14) is not being supported in windows 

**Additional context**
Either we can remove it or we can make it conditional based on platform.

**Comment by parthibd** [comment]
Use firefox. The chromium driver is a bit buggy.
