### ISSUE TITLE
Custom Sticker

### ISSUE THREAD

**Issue by jersonjunior** [alfred82santa/whalesong#116]
Is there any way to send custom stickers,? I can only send the standard Whatsapp stickers, the custom ones are not found in the list of sitckers

**Comment by alfred82santa** [comment]
I guess you must install sticker packeges in order to be able to use them on WhatsAppWeb

**Comment by jersonjunior** [comment]
I may be wrong but it is not possible to install third-party packages in WhatsApp Web according to this subject below: https://github.com/WhatsApp/stickers/issues/210
