### ISSUE TITLE
Sending message to chat not present in collection

### ISSUE THREAD

**Issue by jabolina** [alfred82santa/whalesong#15]
Hi. Is there a way to send a message to chat not present in the ChatCollection?

I've created a method that discover the Chat by it's phone number, based in a method from the mukulhase wrapper. But I was not able to add the found chat in the ChatCollection, or update the ChatCollection in some way.

So what I did was to discover the new chat and send the message at the same method, but again, the chat did not go to the ChatCollection and I did not like this method very much.

There is already a way to send message in this scenery where the chat is not initialized or could you give some help to implement this?

Yeah, this would go against with some spam ethics. :/

**Comment by jabolina** [comment]
Hi. Capturing the UserConstructor in ```index.js``` and passing it to ```ChatCollectionManager```, I did something like this:

```
@command
  async sendMessageToUndiscoveredChat({
    chatId,
    message
  }) {

    const userInfo = new ChatManager.prototype.UserConstructor(chatId);
    const chat = await this.collection.find(userInfo);

    return await ChatManager._sendMessage(
      chat,
      () => chat.sendMessage(message),
      (item) => item.body === message && item.type === 'chat'
    );
  }
```
This is in ```ChatCollectionManager``` because to be in ```ChatManager``` a chat needs to be already "discovered".

The change in ```_sendMessage``` is turned into a static method, where I pass the chat as first parameter, other stuff remains the same.

I'm not on my machine to give you the exact error, but when I do:
```await driver.chats[f'{yournumber}@c.us'].send_text('Hi!')```

An error occurred with: ```Chat not present in ChatCollection```, or something like this.

What I wanted to do is, create the chat, like in the example code above, but then add the created chat into ChatCollection, so it will be able to use ```send_text``` normally. If the created chat is returned to python, and ```send_text``` is called, the same error happens. 

I'm also not sure how UserConstructor works, I suspect that is called when a contact is chosen and a new conversation is started.

**Comment by alfred82santa** [comment]
With #22 pull request, it is possible to chat with unknown users.

```python
await driver.chats.ensure_chat_with_contact(f'{yournumber}@c.us')
await driver.chats[f'{yournumber}@c.us'].send_text('Hi!')
```

**Comment by alfred82santa** [comment]
I didn't have time to test too much... Could you test more?

**Comment by jabolina** [comment]
Sure, I'm not with my machine right now, but tomorrow morning I'll test!

**Comment by jabolina** [comment]
With ```await driver.chats.ensure_chat_with_contact(f'{yournumber}@c.us')```, the Chat is returned correctly, but with ```await driver.chats[f'{yournumber}@c.us'].send_text('Hi!')```, the Chat is not found in collection and the thrown exception is:

```
future: <Task finished coro=<GetChats.monitor_stream() done, defined at getchats.py:30> exception=ManagerNotFound('Manager 5534********@c.us not found',)>
Traceback (most recent call last):
  File "getchats.py", line 44, in monitor_stream
    chat = await self._driver.chats[f'{5534********}@c.us'].send_text('Hi!')
whalesong.errors.ManagerNotFound: Manager 5534********@c.us not found
```

I've tested with no older chats in the phone and with older chats, both of them throw the above exception.

I'll try to do something, maybe in ```js/chat.js```, when the chat is found, insert the new model inside the Chat collection. Later I'll come back with something about it. Thanks!

**Comment by alfred82santa** [comment]
Resolved!
It affected all user chats. Not just new ones.

**Comment by alfred82santa** [comment]
#24

**Comment by alfred82santa** [comment]
I've added a new command to minibot (/send) in order to test this feature. I will close this issue.
