### ISSUE TITLE
No module named 'dirty_models'

### ISSUE THREAD

**Issue by WilliamCampolina** [alfred82santa/whalesong#16]
Hi all, I'm trying to run the minibot, but this is giving the following error
Would you help me
 Version python 3.6.2
@alfred82santa 

![image](https://user-images.githubusercontent.com/7756498/47392996-a4cc0b00-d6f4-11e8-88a7-a341f9089ecf.png)

**Comment by WilliamCampolina** [comment]
I managed to install Whalesong ... but after logging in he can not get the new messages

**Comment by alfred82santa** [comment]
Have you installed requirements? https://github.com/alfred82santa/whalesong#install-library-requirements

**Comment by WilliamCampolina** [comment]
Look at the picture, I sent a text but the driver did not identify the new message
![image](https://user-images.githubusercontent.com/7756498/47433239-67a85d00-d776-11e8-9147-f24a71a46456.png)

**Comment by WilliamCampolina** [comment]
Humm ... It worked.

**Comment by WilliamCampolina** [comment]
Congratulations, I'm really liking the lib,

now you could help me in just one more thing
when i install pip install whalesong it works perfectly
now when I try to execute with the source code it gives the error requesting a file as the image below.


![whalesong-mod](https://user-images.githubusercontent.com/7756498/47442373-a1825f00-d788-11e8-9bc1-9f4fe343bccd.png)

**Comment by alfred82santa** [comment]
please open a new issue... other users could look for the same question.
