### ISSUE TITLE
No such file or directory: 'whalesong/whalesong/js/whalesong.js'

### ISSUE THREAD

**Issue by WilliamCampolina** [alfred82santa/whalesong#17]
when i install
`pip install whalesong ` it works perfectly
now when I try to execute with the source code it gives the error requesting a file as the image below.

![whalesong-mod](https://user-images.githubusercontent.com/7756498/47443782-7a795c80-d78b-11e8-95a1-fc8078d54560.png)

**Comment by alfred82santa** [comment]
You have to rebuild scriptlet after any change if you want to use in Python code.

https://github.com/alfred82santa/whalesong#build-javascript-scriplet

**Comment by WilliamCampolina** [comment]
after the command see the error


![image](https://user-images.githubusercontent.com/7756498/47449047-07c2ae00-d798-11e8-8fee-d12fb15631f2.png)

**Comment by alfred82santa** [comment]
You should follow steps according to readme file:

https://github.com/alfred82santa/whalesong#getting-started

```bash
$ make requirements # it installs python requirement and js requirements
$ make build-js # it builds js scriptlet
```

**Comment by WilliamCampolina** [comment]
it worked ... funny I thought I had tried to install it in venv, but now it worked out ...

Thank you very much and sorry for the obvious questions.
