### ISSUE TITLE
help to send image

### ISSUE THREAD

**Issue by WilliamCampolina** [alfred82santa/whalesong#18]
Congratulations, I'm really liking the lib,
Give me a little help, please.

I want to send an image
I'm doing the following

`self._driver.chats [message.chat.id] .send_media ('/ home / profiles / archive / voucher.jpeg', caption = 'test')`

but I think I'm wrong, what's the right way?

**Comment by alfred82santa** [comment]
`send_media` method needs a file-like object, not a file path:
```python
with open(filename) as f:
    await self._driver.chats[message.chat.id].send_media(f, caption='test')
```

**Comment by WilliamCampolina** [comment]
Look at the console exit, please.


![image](https://user-images.githubusercontent.com/7756498/47729035-3b8d5000-dc3e-11e8-9b6a-04d5ae6e6b9c.png)

**Comment by alfred82santa** [comment]
sorry... it's a binary file...

```python
with open(filename, 'rb') as f:
    await self._driver.chats[message.chat.id].send_media(f, caption='test')
```

**Comment by WilliamCampolina** [comment]
changed the error but it still did not work :(

![image](https://user-images.githubusercontent.com/7756498/47732464-02a4a980-dc45-11e8-8d0b-b591f87930c6.png)

**Comment by alfred82santa** [comment]
try to send content_type='image/jpg'

**Comment by WilliamCampolina** [comment]
It worked perfectly now ...
it looks like you had a problem in the test file,
look at messages with content_type and no content_type
thank you very much


![image](https://user-images.githubusercontent.com/7756498/47734714-a1330980-dc49-11e8-9b1d-7229f4b39337.png)

**Comment by alfred82santa** [comment]
`content_type` tells whatsapp how to process file. If it is unknown, file is treated as binary.
