### ISSUE TITLE
New Whatsapp Status (Stories)

### ISSUE THREAD

**Issue by alfred82santa** [alfred82santa/whalesong#41]

**Comment by jabolina** [comment]
That's interesting, I'll do some research on this

**Comment by alfred82santa** [comment]
I was looking at code. They looks like a regular message with a caption. And it looks it is not possible to create new stories from WhatsAppWeb...

**Comment by alfred82santa** [comment]
Ahh they call them `statusV3`

**Comment by jabolina** [comment]
Found it

![image](https://user-images.githubusercontent.com/13581903/52447179-29f9f500-2b17-11e9-8225-c681f2765cae.png)

I have to write my monography (i think that's the word in english), but tomorrow i'll look more into it.

Thanks!

**Comment by jabolina** [comment]
Hey, I've managed to create some of the functionalities that looked more interesting. But I'm not sure which one will be better. When we want to get all the read/unread statuses, it's better to return an iterator or it's better just to await and return all the objects as an array?

I've implemented returning the iterator, and at this basic example I've created just to test it's something like [this](https://github.com/jabolina/whalesong/blob/master/examples/getstatusv3.py#L59).

What do you think?

**Comment by alfred82santa** [comment]
You don't need to implement `get_status` method. `StatusV3CollectionManager` is a collection manager, so it inherits `get_items` method.

**Comment by alfred82santa** [comment]
https://github.com/jabolina/whalesong/blob/master/whalesong/managers/status_v3.py#L61 <== wow! you just need status_id and contact_id. You could get id objects from js collections,

**Comment by jabolina** [comment]
Oh, I really messed up. I'm having trouble because the StatusV3 object looks like a Chat object, and the messages are the image/text posted in the status. But I can't manage to get the messages objects back in the python.
