### ISSUE TITLE
Remote Selenium

### ISSUE THREAD

**Issue by marcelocecin** [alfred82santa/whalesong#57]
hi there
is possible to run with Remote Selenium ?
thanks

**Comment by alfred82santa** [comment]
Not yet... I guess it will be easy to create a new driver for that. But I don't sure why anyone could need it. It looks better to install whalesong on remote machine and interact with it by a websocket or something like that. I don't understand why to use a remove browser. 

On the other hand, I will remove support for selenium in next versions. It doesn't fit well with whalesong.
