### ISSUE TITLE
send_media with audio file fails / How to send audio?

### ISSUE THREAD

**Issue by DSchndr** [alfred82santa/whalesong#58]
When you send any file with audio mime type sending fails.
(Seems like the download function in the minibot example also cannot handle mp3 send.)

How about an send_audio function where the file gets sent like an voice recording?

**Comment by alfred82santa** [comment]
Have you tried an ogg audio file?

**Comment by alfred82santa** [comment]
You are right Whalesong can not send audio files like voice recordings, I mean, it can not send PushToTalk messages. 
But, I've tested minibot with this message:

```
/download https://sample-videos.com/audio/mp3/crowd-cheering.mp3
```
And it works like a PushToTalk message. Examples are just examples, they don't try to be perfects, so it is possible you are using a url which response with a composed `content-type` header and whatsappweb fails. Could you post your url?

**Comment by DSchndr** [comment]
i think it was https://sample-videos.com/audio/mp3/crowd-cheering.mp3

**Comment by alfred82santa** [comment]
![imatge](https://user-images.githubusercontent.com/574291/51805345-71a59480-226c-11e9-9e55-e9fc8e58aa1b.png)

Does it still happen to you? I will need more info.

**Comment by DSchndr** [comment]
Minibot and my own bot still fail to send the file as ptt message.
Trying to send an mp3 over waweb also fails in my case ("unsupported file"), so maybe there is something in waweb code that is being retarded?

``` future: <Task finished coro=<Minibot.make_download() done, defined at examples/minibot.py:116> exception=UnknownError()>
Traceback (most recent call last):
  File "examples/minibot.py", line 133, in make_download
    message.id)))
whalesong.errors.UnknownError

**Comment by alfred82santa** [comment]
Well, if WhatsApp Web fails there is nothing we can do. But is strange, it works in my case. Which OS do you use? And browser?

**Comment by DSchndr** [comment]
Firefox 64.0 (64-bit), Ubuntu 18.04 LTS

MP4 upload doesn't work in selenium window, but in normal window it works which is kinda wierd.
In chrome everything works, so i think maybe firefox version is a little bit too old and waweb code detects this or firefox interferes with it somehow?

**Comment by alfred82santa** [comment]
Finally, I've found the problem, at least in Firefox. Default Firefox profile template disabled all codecs. Now it should work for all codecs supported by ffmpeg.

On the other hand, I guess we can not solve problem with h.264 codec on Chronium: https://www.chromium.org/audio-video

I didn't find way to enable ffmpeg at runtime.

**Comment by alfred82santa** [comment]
Could you test it?

**Comment by alfred82santa** [comment]
Maybe, best option would be transcode files before to send them...

**Comment by DSchndr** [comment]
Thanks, with enabled codecs everything works on firefox!

**Comment by tulssinep** [comment]
Hey, running into the same issue with Safari on Desktop at the moment. I can send MP3 but not OGG. Is there anything I can do about it or is there a list of supported audio codecs?

**Comment by DSchndr** [comment]
Use ffmpeg to transcode the files into mp3 format or use firefox.
