### ISSUE TITLE
Start Driver with headless = True

### ISSUE THREAD

**Issue by Tingaev** [alfred82santa/whalesong#64]
Hello
I don't understand how I can run one of example with "headless=True".
I am try start minibot.py in docker container, but output was empty.
Which the moment I can call method get_qr() and get him?

**Comment by alfred82santa** [comment]
Well, minibot does not implement that functionality. But you could look at https://github.com/alfred82santa/whalesong/blob/master/examples/statemonitor-chromium.py#L65

It monitors `ref` field, which is represented in qr.

**Comment by Tingaev** [comment]
`New REF value: 1@7Fa4UujqTgeeuzMcb4sM//kdbsk/KlqTWLXTEgiPGlwjR0UHh9x3Pz/u`
It is code, which I can use for create image, and I get Qr code?

**Comment by Tingaev** [comment]
Thank you so much 🙂
