### ISSUE TITLE
start of two bots

### ISSUE THREAD

**Issue by Tingaev** [alfred82santa/whalesong#65]
How I can run two bots?
I try create two objects Minibot and start in one event loop, but I have error

**Comment by alfred82santa** [comment]
WhatsappWeb only can be connected once at same time. It means, you can not run two bots with same phone. On the other hand, it is not possible to connect same browser to two WhatsappWebs (to two phones). So, if you want to run two minibot you need two phone and two browser profiles.

You can choose directory profile for each one at:

https://github.com/alfred82santa/whalesong/blob/master/examples/minibot.py#L20

**Comment by Tingaev** [comment]
Thanks
