### ISSUE TITLE
flask sample

### ISSUE THREAD

**Issue by marcelocecin** [alfred82santa/whalesong#70]
hi there
is possible to use flask / tornado / bottle / django to implement an API with this library ?
thank you

**Comment by alfred82santa** [comment]
It is possible to create an http service, but not with flask, bottle or django. I'm not sure with tornado. Whalesong is an asynchronous library, so an async framework must be used: aiohttp, quart, etc... However, http does not fit well with bi-directional apps. It must use websockets or web hooks.

I have no plans, yet.

**Comment by parthibd** [comment]
WebSockets sounds like a great idea for communicating with whalesong. :)
