### ISSUE TITLE
MessageInfoManager

### ISSUE THREAD

**Issue by jesusvalverde** [alfred82santa/whalesong#76]
Can somebody post a small example on how I get the MessageInfoManager, the issue is to get the status of a message [delivery, read]

**Comment by alfred82santa** [comment]
MessegeManager has a method in order to fetch info. https://whalesong.readthedocs.io/en/latest/api/message.html#whalesong.managers.message.MessageManager.fetch_info

You must call it before try to use MessageInfoManager stored on field `info` of a MessageManager.

**Comment by jabolina** [comment]
I've always did something like [this](https://github.com/alfred82santa/whalesong/blob/master/examples/getmessages.py#L59) to see the message status

**Comment by jesusvalverde** [comment]
Solved AND working ..
