### ISSUE TITLE
How to refresh QR code?

### ISSUE THREAD

**Issue by parthibd** [alfred82santa/whalesong#78]
Suppose calling `await driver.qr()` times out . How to refresh the qr code ? Is there an api to refresh the qr ?

**Comment by jabolina** [comment]
When the QR expires and need to be clicked, do something like [this](https://github.com/alfred82santa/whalesong/blob/master/examples/statemonitor.py#L57)

**Comment by parthibd** [comment]
Thanks! That solves my problem.
