### ISSUE TITLE
Few questions regarding functionality

### ISSUE THREAD

**Issue by parthibd** [alfred82santa/whalesong#79]
I have a few questions to ask .

1 . Is there a way to ensure that the contact id exists?
2. How to avoid sending to a non existent contact id ?

**Comment by jabolina** [comment]
Every time I needed to verify a given contact number, I've used [this method](https://github.com/alfred82santa/whalesong/blob/master/js/src/whalesong/wap.js#L12).

So you can use this to verify the contact existence to send a message.

**Comment by parthibd** [comment]
Thanks for reference . Solves my problem precisely.
