### ISSUE TITLE
API for logging out 

### ISSUE THREAD

**Issue by parthibd** [alfred82santa/whalesong#87]
Is there a method to log out ?

**Comment by alfred82santa** [comment]
Nop, I haven't implemented it. I guess it is easy to implement. It is just a method in `conn` or `stream` object. Do you want try to do it? or do you prefer I do it?

**Comment by parthibd** [comment]
Let me try it out . I'll let you know if I run into troubles.

**Comment by parthibd** [comment]
Made a pull request implementing the functionality .
