### ISSUE TITLE
Get quoted message object

### ISSUE THREAD

**Issue by jabolina** [alfred82santa/whalesong#9]
Hi, is there a way to get the quoted message object, instead of only the *quoted_stanza_id*, wich references the id of the quoted message. The thing I saw which maybe could affect is [this property](https://github.com/alfred82santa/whalesong/blob/master/whalesong/managers/message.py#L151).

But turning the property to True, and executing the make commands again I only obtained the quoted message id. 

Is there a way to get the full object body?

**Comment by alfred82santa** [comment]
I think you should load message using `quoted_stanza_id`:

```python
qouted_msg = await self._driver.messages.get_item_by_id(msg.quoted_stanza_id)
```

**Comment by alfred82santa** [comment]
The property you mention is just to tell frontend whether message should show the `forwarded` tag.

**Comment by jabolina** [comment]
Thank you, I had to do a little trick to work, only the *quotedStanzaId*, could not find the element. So I did this:

```
if message.quotedStanzaID is not None:
    quoted_id = message.id[:message.id.index('@c.us_')] + '@c.us_' + message.quotedStanzaID
    quoted_message = await self._driver.messages.get_item_by_id(quoted_id)
```

When the item id was not found, the exception throwing in js had an error, I fixed that too.

Thank you very much!!

**Comment by jabolina** [comment]
Actually, the quoted id is different, depending if the quoted is sent by me or other. So I did this:

```
if message.quotedStanzaID is not None:
    quoted_id = message.id[:message.id.index('@c.us_')] + '@c.us_' + message.quotedStanzaID \
        if message.quotedParticipant == message.chat.id else \
        'true_' + message.chat.id + '_' + message.quotedStanzaID

    quoted_message = await self._driver.messages.get_item_by_id(quoted_id)
```

So, this will work just fine.
